### PR TITLE
Implement --dont-skip

### PR DESCRIPTION
**Pull request by WaylonWalker**
I attemtped to implement `--force`, but I am getting the following error.  I assume that it it something that is currently in flux.  I removed any of my code that did anything and it was still there.

```
 + Skipping install/python.
 + Executing install:
 |  /dev/fd/62: line 14: syntax error: unexpected end of file
 |  /dev/fd/63: line 15: syntax error: unexpected end of file
Task install failed!
```

If it is easier to implement yourself, no hard feelings.

**EDIT**

This is to solve issue https://github.com/kennethreitz/bake/issues/7

### CODE REVIEW

**Comment by kennethreitz** [comment]
how is this different than `--yes`?

**Comment by WaylonWalker** [comment]
force will force the task to run even if skip triggers.


  --yes                    Set medium–security prompts to yes.
  --force -f              Forces task to run even if skip key hasnt changed


bakeforce

**Comment by WaylonWalker** [comment]
Switched it up based on your comment on the issue

```
  --yes                    Set medium–security prompts to yes.
  --dont-skip          Forces task to run even if skip key hasnt changed
```

bakedontskip

**Comment by kennethreitz** [comment]
Let me get CI working :)

**Comment by kennethreitz** [comment]
rebase?

**Comment by WaylonWalker** [comment]
Had some time to read through the tests and understand what was broken.  Tests are now passing, Please let me know if there are any other changes I can make.

**Pull request closed without merging**
